<?php require_once './templates/header.phtml'?>

<h1  class="text-center text-violet">Nuestras Categorias son:</h1>


<table class="table table-striped table-hover" style="background-color: #aee6de;">
    <thead>
        <tr>
            <th style="background-color: #40a797";> Nombre Categoria </th>
            <th style="background-color: #40a797";>Descripcion</th>
            <th style="background-color: #40a797";>Fecha de creacion</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list as $item):?>
            
                
                <tr>
                    <td>
                        <span style="
                        font-weight:800;
                        font-size:15px;"><?= $item->nombre_categoria ?>
                        </span> 
                    </td>
                    <td><?= $item->descripcion ?></td>
                    <td>
                        <span style="
                        font-weight:800;
                        font-size:15px;"><?= $item->fecha_creacion ?>
                        </span>    
                    </td> 
                </tr>
                  

        <?php endforeach?> 
    </tbody>
</table>

<?php require_once './templates/footer.phtml'?>