<?php require_once './templates/header.phtml'?>
<h2 class="text-center text-violet">Agregar Categoria:</h2>


<form method="post" action="addCategoria" class="form-control form-control-sm"  style="background-color:#aee6de;">
    <div class="mb-3">
        <label for="nombre" class="form-label">Ingrese un nombre de categoria</label>
        <input type="text" class="form-control" name="nombre_categoria" id="nombre">
           <label for="nombre" class="form-label">Ingrese descripcion de la categoria</label>
        <input type="text" class="form-control" name="descripcion" id="descripcion">
        <label for="nombre" class="form-label">Seleccione fecha de creacion de la categoria</label>
        <input type="date" class="form-control "name="fecha_creacion" id="fecha_creacion">
        
    </div>
    
    <button type="submit" class="btn btn-outline-success" style="background-color:#146c43; color:white; border:none; border-radius:10px;">Agregar</button>
</form>

<h1  class="text-center text-violet">Nuestras Categorias son:</h1>

<table class="table table-striped table-hover" style="background-color: #aee6de;">
    <thead>
        <tr>
            <th style="background-color: #40a797";>Nombre Categoria</th>
            <th style="background-color: #40a797";>Descripcion</th>
            <th style="background-color: #40a797";>Fecha de creacion</th>
            <th style="background-color: #40a797";></th>
            <th style="background-color: #40a797";></th>
            <th style="background-color: #40a797";></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list as $item):?>
                <tr>
                    <td><?= $item->nombre_categoria ?></td>
                    <td><?= $item->descripcion ?></td>
                    <td><?= $item->fecha_creacion ?></td>
                    <td><a href="editCategoria/<?= $item->id_categoria?>" class="btn btn-success">Editar</a></td>
                    <td><a href="removeCategoria/<?= $item->id_categoria?>" class="btn btn-danger">Borrar</a></td>  
                </tr>       

        <?php endforeach?> 
    </tbody>
</table>
<?php require_once './templates/footer.phtml'?>
