<?php require_once './templates/header.phtml'; ?>

<h1 class="mb-4">Edite el producto:</h1>

<form method="post" action="updateProducto/<?=$id?>"
      class="form-control form-control-sm p-4 shadow"
      style="background-color:#aee6de;" border-radius:15px;">

    <label class="h5 text-dark mb-2">Ingrese el nombre del producto</label>
    <input class="form-control mb-3" type="text" name="nombre" id="nombre">

    <label class="h5 text-dark mb-2">Ingrese una categoria</label>
    <select class="form-select mb-3" name="categoria" id="categoria">
        <?php foreach($listCategorias as $item): ?>
            <option value="<?= $item->id_categoria ?>">
                <?= $item->nombre_categoria ?>
            </option>
        <?php endforeach ?>
    </select>

    <label class="h5 text-dark mb-2">Ingrese su precio</label>
    <input class="form-control mb-3" type="number" name="precio" id="precio">

    <label class="h5 text-dark mb-2">Ingrese el talle</label>
    <input class="form-control mb-3" type="text" name="talle" id="talle">

    <label class="h5 text-dark mb-2">Ingrese el color</label>
    <input class="form-control mb-3" type="text" name="color" id="color">

    <label class="h5 text-dark mb-2">Ingrese la marca</label>
    <input class="form-control mb-4" type="text" name="marca" id="marca">

    <button type="submit"
            class="btn px-4"
            style="
            background-color:#146c43;
            color:white;
            border:none;
            border-radius:10px;">
        Actualizar
    </button>

</form>

<?php require_once './templates/footer.phtml'; ?>