<?php require_once './templates/header.phtml'?>

<h1 class="mb-4">Editar categoria:</h1>

<div class="form-control p-4 shadow"
     style="
     background-color:#aee6de;
     border-radius:15px;">

    <ul class="list-group border-0">

        <li class="list-group-item border-0"
            style="background-color:#aee6de;">

            <h4 class="mb-4" style="color:black;">
                Nombre actual:
                <span class="fw-bold">
                    <?= $categoria->nombre_categoria ?>
                </span>
            </h4>

            <form method="post"
                  action="updateCategoria/<?=$id?>">

                <label class="h5 mb-2" style="color:black;">
                    Ingrese el nuevo nombre
                </label>

                <input type="text"
                       class="form-control mb-4"
                       name="nombre"
                       id="nombre"
                       required>

                <button type="submit"
                        class="btn px-4"
                        style="
                        background-color:#146c43;
                        color:white;
                        border:none;
                        border-radius:10px;">
                    Actualizar
                </button>

            </form>

        </li>

    </ul>

</div>

<?php require_once './templates/footer.phtml'?>