
<!-- main footer -->
<footer class="bg-dark text-white text-center py-3 mt-5">
    <p class="mb-1 fs-4 fw-light" 
       style="color:#87CEEB; letter-spacing:2px; font-family:'Trebuchet MS', sans-serif;">
        HUSTLE CULTURE
    </p>
    <small class="text-secondary">
        © 2026 All rights reserved
    </small>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>