<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>HUSTLE CULTURE</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm py-3">
            <div class="container">

                <a 
                   class="navbar-brand fw-bold fs-3 px-3 py-2" href="#"
                   style="
                   color: #18b5c0;
                   letter-spacing:2px;
                   border:1px solid #18b5c0;
                   border-radius:12px;">
                   HUSTLE CULTURE
                </a>

                <button class="navbar-toggler" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav gap-2">

                        <li class="nav-item">
                            <a class="nav-link text-white fw-semibold" href="categorias" >
                                CATEGORIAS
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white fw-semibold" href="home">
                                PRODUCTOS
                            </a>
                        </li>

                        <?php if (!isset($_SESSION['USER_ID'])) : ?>

                        <li class="nav-item">
                            <a class="nav-link fw-semibold px-3 py-2"
                               href="login"
                               style="
                               background-color:#146c43;
                               color:white;
                               border-radius:10px;">
                                LOGIN
                            </a>
                        </li>

                        <?php else : ?>

                        <li class="nav-item">
                            <a class="nav-link text-danger fw-semibold" href="logout">
                                LOGOUT (<?= $_SESSION['USER_USER'] ?>)
                            </a>
                        </li>

                        <?php endif ?>

                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <main class="container mt-4">