<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="user">User</label>
            <input type="user" required class="form-control" id="user" name="user" aria-describedby="userHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                   <a href="home/" type="button" class='btn btn-danger ml-auto'>Volver al inicio</a>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>