<?php require_once './templates/header.phtml' ?>
  <?php $producto = $productos->nombre_producto ?>


    <h3 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Producto: <?= $producto ?></h3>
    <?php if($producto == 'Jersey Nro 52'):?>
            <img class="d-block mx-auto img-fluid" src="https://www.broskiclothing.com/cdn/shop/products/BroskiClothing-NFLLegacyJerseyBaltimoreRavensRayLewis_52-MitchellandNessThrowback.jpg?v=1642039388&width=493" alt="Jersey Nro 52" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;"> Jersey Futbol Americano | Khalil Mack | Chicago Bears | #52 | Talle XL | Prenda Vintage</h4>
             
    <?php  elseif($producto == 'Trackpant '):?>
            <img class="d-block mx-auto img-fluid" src="https://i.ebayimg.com/images/g/6k4AAeSwQ7FpW3o0/s-l1600.webp" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Trackpant | Adidas | Talle L | Prenda Vintage </h4>

    <?php  elseif($producto == 'Hoodie Yankees'):?>
            <img class="d-block mx-auto img-fluid" src="https://www.marveljacket.com/wp-content/uploads/2024/03/New-York-Yankees-Hoodie-1.jpg" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Hoodie | New York Yankees | Talle L | Prenda Nueva</h4>

    <?php  elseif($producto == 'Camiseta Barcelona Nro 10 Retro'):?>
            <img class="d-block mx-auto img-fluid"  src="https://www.picclickimg.com/images/g/HvcAAeSwIY9pqfS2/s-l1600.jpg" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Camiseta Barcelona | Rivaldo | Numero 10 | Talle XL | Edicion 1995</h4>

    <?php  elseif($producto == ' Hoodie retro'):?>
            <img class="d-block mx-auto img-fluid" src="https://brimportados.com.ar/wp-content/uploads/2025/04/WhatsApp-Image-2025-04-07-at-15.58.14.jpeg" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Hoodie | Nike | Talle XXL | Prenda Vintage</h4>

    <?php  elseif($producto == 'Chomba Polo'):?>
            <img class="d-block mx-auto img-fluid" src="https://acdn-us.mitiendanube.com/stores/889/200/products/img_3548-d649863c18c91b9a8617787907818732-1024-1024.webp" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Chomba | Polo | Talle M | Prenda Vintage</h4>
    
    <?php  elseif($producto == 'Jersey Nro 22'):?>
            <img class="d-block mx-auto img-fluid" src="https://http2.mlstatic.com/D_NQ_NP_2X_700982-MLA98404754883_112025-F.webp" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Jersey Futbol Americano | Harris | Steelers | #22 | Talle L | Prenda Nueva</h4>
   
    <?php  elseif($producto == 'Pantalon Rompeviento retro'):?>
            <img class="d-block mx-auto img-fluid" src="https://i.pinimg.com/736x/8f/d9/da/8fd9daa10bc44da6992cba9dccc54d64.jpg" alt="" srcset="">
            <h4 class="text-white text-center py-2 rounded" style="background-color:#40a797;">Pantalon Rompeviento | Nike | Talle L | Prenda Vintage</h4>



    <?php else: ?>
        <h4>Esta categoria no tiene imagen adjunta</h4>
    <?php endif ?>


<?php require_once './templates/footer.phtml' ?>