<?php 
require_once './templates/header.phtml'?>



<form method="post"
      action="filtrarProducto"
      class="form-control p-4 mb-4 shadow"
      style="
      background-color:#aee6de;
      border-radius:15px;">
    <div class="row align-items-center g-3">
        <div class="col-auto">
            <label for="filtroCategoria"
                   class="h5 mb-0"
                   style="color:black;">
                Filtrar por:
            </label>
        </div>

        <div class="col-md-4">
            <select class="form-select"
                    name="filtroCategoria"
                    id="filtroCategoria">
                <option value="">
                    Todas las categorías
                </option>
                <?php foreach($categorias as $item): ?>
                    <option value="<?= $item->id_categoria ?>">
                        <?= $item->nombre_categoria ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="col-auto">
            <button type="submit"
                    class="btn px-4"
                    style="
                    background-color:#146c43;
                    color:white;
                    border:none;
                    border-radius:10px;">
                    Filtrar
            </button>
        </div>

    </div>

</form>

<table class="table table-striped table-hover" style="background-color: #aee6de;">
    <thead>
        <tr>
            <th style="background-color: #40a797";>Nombre Producto</th>
            <th style="background-color: #40a797";>categoria</th>
            <th style="background-color: #40a797";>Precio</th>
            <th style="background-color: #40a797";>Talle</th>
            <th style="background-color: #40a797";>Color</th>
            <th style="background-color: #40a797";>Marca</th>
            <th style="background-color: #40a797";></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list as $item):?>
            <tr>
                <td><?= $item->nombre_producto ?></td>
                <td><?= $item->nombre_categoria ?></td>
                <td>
                    <span style="
                        font-weight:800;
                        font-size:15px;">
                        $<?= $item->precio ?>
                    </span>
                </td>
                <td>
                    <span style="
                    font-weight:400;
                    font-size:14px;
                    font-family:'Arial Black', sans-serif;
                    letter-spacing:1px;">
                    <?= $item->talle ?>
                    </span>
                </td>
                <td><?= $item->color ?></td>
                <td><?= $item->marca ?></td>
                <td><a href="showProducto/<?= $item->id ?>" class="btn btn-success" style="background-color:#146c43;" >Ver Producto</a></td>
            </tr>
        <?php endforeach?> 
    </tbody>
</table>

<?php require_once './templates/footer.phtml' ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
